### ISSUE TITLE
Hi 👋, can you please remove the google API key from this repo?

### ISSUE THREAD

**Issue by richhiggins** [HarryCanCode/coop-revised#1]
It's located in this file, 

[https://github.com/HarryCanCode/coop-revised/blob/f715cec3bc1f32f6f3f14be5ed68bfdad7734c30/Co-operate%20Website%20Revised/Webpages/Co-operate_files/js](https://github.com/HarryCanCode/coop-revised/blob/f715cec3bc1f32f6f3f14be5ed68bfdad7734c30/Co-operate%20Website%20Revised/Webpages/Co-operate_files/js)

I got an alert from google.

cheers!

Rich

**Comment by HarryCanCode** [comment]
Hey Rich!

I have now deleted the google API key from the repo. 
Apologies for taking so long, I am new to Github and I am continually expanding my knowledge on how to use this website efficiently.


Cheers!

Harry

**Comment by richhiggins** [comment]
no problem, and thanks for this 🙂
